#pragma once
#include "EpisodeStateBytesForTesting.h"
#include "SHitResult.h"
#include "PhysicalContactConstraint.h"
#if !UE_BUILD_SHIPPING
namespace Speed {
template<> struct FEpisodeFieldCodec<FKinematicState> { static void Write(TArray<uint8>& O,const FKinematicState& X) { FEpisodeStateBytesForTesting::Add(O,X.Location);FEpisodeStateBytesForTesting::Add(O,X.Velocity);FEpisodeStateBytesForTesting::Add(O,X.Acceleration);FEpisodeStateBytesForTesting::Add(O,X.Rotation);FEpisodeStateBytesForTesting::Add(O,X.AngularVelocity);FEpisodeStateBytesForTesting::Add(O,X.AngularAcceleration); } };
template<> struct FEpisodeFieldCodec<SHitResult> { static void Write(TArray<uint8>& O,const SHitResult& X) { FEpisodeStateBytesForTesting::Add(O,X.bHit);FEpisodeStateBytesForTesting::Add(O,X.bBlockingHit);FEpisodeStateBytesForTesting::Add(O,X.Location);FEpisodeStateBytesForTesting::Add(O,X.ImpactPoint);FEpisodeStateBytesForTesting::Add(O,X.ImpactNormal);FEpisodeStateBytesForTesting::Add(O,X.TOI);FEpisodeStateBytesForTesting::Add(O,X.FaceIndex);FEpisodeStateBytesForTesting::Add(O,X.Component);FEpisodeStateBytesForTesting::Add(O,X.SubBody);FEpisodeStateBytesForTesting::Add(O,X.bStartPenetrating);FEpisodeStateBytesForTesting::Add(O,X.PenetrationDepth);FEpisodeStateBytesForTesting::Add(O,X.GeometricErrorBoundCm);FEpisodeStateBytesForTesting::Add(O,X.bSurfaceNormalMayVary);FEpisodeStateBytesForTesting::Add(O,X.ContactPointThis);FEpisodeStateBytesForTesting::Add(O,X.ContactPointOther);FEpisodeStateBytesForTesting::Add(O,X.ContactFeatureThis);FEpisodeStateBytesForTesting::Add(O,X.ContactFeatureOther);FEpisodeStateBytesForTesting::Add(O,X.ContactFeatureIndexThis);FEpisodeStateBytesForTesting::Add(O,X.ContactFeatureIndexOther);FEpisodeStateBytesForTesting::Add(O,X.SourceId);FEpisodeStateBytesForTesting::Add(O,X.SurfaceId);FEpisodeStateBytesForTesting::Add(O,X.FeatureId);FEpisodeStateBytesForTesting::Add(O,X.PrimitiveId);FEpisodeStateBytesForTesting::Add(O,X.CanonicalGroupId);FEpisodeStateBytesForTesting::Add(O,X.MaterialId);FEpisodeStateBytesForTesting::Add(O,X.FrameTag);FEpisodeStateBytesForTesting::Add(O,X.InFrameTag); } };
template<> struct FEpisodeFieldCodec<FPhysicalContactConstraint> { static void Write(TArray<uint8>& O,const FPhysicalContactConstraint& X) { FEpisodeStateBytesForTesting::Add(O,X.Normal);FEpisodeStateBytesForTesting::Add(O,X.ContactPoint);FEpisodeStateBytesForTesting::Add(O,X.OtherComponent);FEpisodeStateBytesForTesting::Add(O,X.SourceSubBody);FEpisodeStateBytesForTesting::Add(O,X.PenetrationDepth);FEpisodeStateBytesForTesting::Add(O,X.TOI);FEpisodeStateBytesForTesting::Add(O,X.PairKey);FEpisodeStateBytesForTesting::Add(O,X.FramesSinceSeen);FEpisodeStateBytesForTesting::Add(O,X.bPersistent); } };
}
#endif
